### PR TITLE
Stefan jum/add develop section

### PR DESCRIPTION
**Pull request by StefanJum**
Rebased on top of #315 to have the linter output available. Will rebase after that is merged.

### CODE REVIEW

**Comment by StefanJum** [comment]
Rebased on top of staging.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Comment by Mic92** [comment]
Will main automatically deployed to https://unikraft.org/?

**Comment by razvand** [comment]
> Will main automatically deployed to https://unikraft.org/?

@Mic92 , eventually, yes. It's not yet the case, it requires a manual run.

**Pull request merged**
