### PR TITLE
Remove public folder

### PR DESCRIPTION
**Pull request by razvand**
The `public/` folder is not used. Static content is located in the `static/` folder.

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
The `unikraft-bot-assignment.png` and `unikraft-concourse-builds.png` files are not present in the `static` directory and are used in the [review-process](https://unikraft.org/docs/contributing/review-process/#stages-of-the-code-review-process) page ([source code](https://github.com/unikraft/docs/blob/main/content/en/docs/contributing/review-process.md?plain=1#L91)).
They should be moved into `static/assets/img`, not deleted.

It seems that there are a lot of duplicates in `public/` and `static/`, we need to delete the duplicates and move the ones that are not present in `static/` if we want to remove the `public/` folder.

**Comment by razvand** [comment]
@StefanJum , makes sense, I will copy the `public/` files to `static/` to have all in one place.

**Comment by razvand** [comment]
@StefanJum , please see now.

**Review by StefanJum — APPROVED** [review]
Looks good now.
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by cristian-vijelie** [comment]
You deleted [unikraft-bot-checkpatch.png](https://github.com/unikraft/docs/pull/92/files#diff-48070bab76e7f9532fdd2d3b07613069373577f24eede230dc9415c226095dde). Is it intended?

**Pull request merged**
