### PR TITLE
docs/getting-started: Remove one unnecessary word

### PR DESCRIPTION
**Pull request by tibeer**
Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
Hi @tibeer, thanks for this.
Please update your commit message to follow the format described [here](https://unikraft.org/docs/contributing/submitting-changes/#commits). Add `docs/getting-started:` at the beginning and remove the dot at the end.
It all looks good besides that.

**Comment by tibeer** [comment]
Sure, no problem.

**Review by StefanJum — CHANGES_REQUESTED** [review]
Also use present tense (`Remove` instead of `removed`), sorry for missing it :)

**Comment by tibeer** [comment]
no worries, fixed.

**Review by StefanJum — APPROVED** [review]
All good now, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
