### PR TITLE
Fixed typo in Coding Style page

### PR DESCRIPTION
**Pull request by TaeminHa**
This pr fixes the typo in "Coding Style" page under "Contributing" of the main website.

"In the future, me might provide... change this code." -> "In the future, we might provide... changes this code."

I'm new to open source, and wasn't really sure if creating an issue was a good idea since it's a single word change.
I'll create one if requested by the reviewers :)

Signed-off-by: Taemin Ha taemin.ha@utexas.edu

### CODE REVIEW

**Review by andraprs — COMMENTED** [review]
Thank you for the contribution, @TaeminHa. :)

Here are a couple of items with regard to the commit message:

* Please include the Signed-off-by tag in the commit message body.
* Please include in the commit title, at the beginning, the component that is updated e.g. "docs/contributing: Fix typo in Coding Style page".
* Could check out, for example, this reference [1], for a set of good practices to consider when writing a commit message.

[1] https://cbea.ms/git-commit/

**Comment by TaeminHa** [comment]
Thank you for the feedback! It should be changed now.

**Comment by andraprs** [comment]
> Thank you for the feedback! It should be changed now.

You are welcome. Thank you for the updates.

Let's see. So there are now 2 commits in the PR, the second one having no changes [1]. There should be only one commit, that includes the documentation text change from the first commit [2] and the commit message from the second commit [1]. For this, one option is to use the "squash" functionality of git [3] [4]. And please enclose in "< >" the email from the "Signed-off-by" tag from the commit message ( e.g. Signed-off-by : Taemin Ha \<taemin.ha@utexas.edu> ).

[1] https://github.com/unikraft/docs/pull/203/commits/5bbfe3d773ef3ac7cd28245573f3c2378e883bbd
[2] https://github.com/unikraft/docs/pull/203/commits/edfa60064cb832194dc253a20fd0f1c0cd545fa3
[3] https://git-scm.com/docs/git-rebase#_interactive_mode
[4] https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by TaeminHa** [comment]
Hi!

I just squahsed the 2 commits "5bbfe3d" and "edfa600" into 1.
I noticed that my forked repo is 1 commit behind Unikraft/docs, but wasn't sure if I should sync since that would get rid of the commits.
If this is the case, please let me know as I will create a new PR.

Thank you!

**Comment by andraprs** [comment]
> Hi!
> 
> I just squahsed the 2 commits "5bbfe3d" and "edfa600" into 1.
> 
> I noticed that my forked repo is 1 commit behind Unikraft/docs, but wasn't sure if I should sync since that would get rid of the commits.
> 
> If this is the case, please let me know as I will create a new PR.
> 
> Thank you!

Hi, @TaeminHa,

Thank you for the updated PR.

Just one more thing, please adjust the Signed-off-by tag. Only the e-mail should be enclosed in "<>" [1].

Signed-off-by : \<taemin Ha taemin.ha@utexas.edu> => Signed-off-by: Taemin Ha \<taemin.ha@utexas.edu>

Indeed, this should be the usual case, to have an up-to-date fork / branch. For the change from this PR, I think the sync is not needed for now. There is a typo fix in this PR and the mentioned commit [2] from the Unikraft docs repository doesn't modify the component that is included in this PR (the coding style web page). So there shouldn't be possible codebase changes conflicts.

Thank you.

[1] https://unikraft.org/docs/contributing/submitting-changes/
[2] https://github.com/unikraft/docs/commit/3804f6013c06a6a9d99b629c3f3496b15b6a6d32

**Comment by TaeminHa** [comment]
Hi, @andraprs,

I apologize for the minor mistakes. I have fixed the commit message so that the email is enclosed by <>
I will make sure to follow the contribution guidelines next time I submit a PR to the repository.

Sorry for the inconvenience, and again, thank you for your kind feedbacks.

Best,
Taemin Ha

**Comment by andraprs** [comment]
> Hi, @andraprs,
> 
> I apologize for the minor mistakes. I have fixed the commit message so that the email is enclosed by <> I will make sure to follow the contribution guidelines next time I submit a PR to the repository.
> 
> Sorry for the inconvenience, and again, thank you for your kind feedbacks.
> 
> Best, Taemin Ha

No worries, this is part of the continuous learning. The commit looks good now, thank you for the updates.

You are welcome, happy to help.

**Review by StefanJum — APPROVED** [review]
Thank you @TaeminHa, sorry for taking a long time to review.
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
