### PR TITLE
Add node version as ARG to Dockerfile

### PR DESCRIPTION
**Pull request by RaduNichita**
* Updates node version to 14.
* Adds the node version as an `ARG` to Dockerfile

### CODE REVIEW

**Comment by StefanJum** [comment]
@LucaSeri @John-Ted I know you had an issue with building inside a container, can you check if this pr fixes it?

**Review by John-Ted — APPROVED** [review]
This fixes my issue, the documentation builds and deploys successfully using the container.
I get some warnings relating to some incompatible versions and optional dependencies, but they do not appear to affect functionality.

Reviewed-by: Ioan-Teodor Teugea ioan_teodor.teugea@stud.acs.upb.ro

**Review by LucaSeri — APPROVED** [review]
Thank you @RaduNichita. This fixes the issue for me.

Reviewed-by: Luca Seritan <luca.seritan@gmail.com>

**Review by StefanJum — CHANGES_REQUESTED** [review]
@RaduNichita please update the commit message and say why this was necessary, I'll merge after that.

**Comment by RaduNichita** [comment]
I updated the commit message, @StefanJum. Please check if eveything is OK now :pray:

**Pull request merged**
