### PR TITLE
Stefan jum/add contributing

### PR DESCRIPTION
**Pull request by StefanJum**
Currently rebased on top of #315 for the linter output. Will rebase once that is merged.

### CODE REVIEW

**Comment by StefanJum** [comment]
Rebased on top of staging.

**Comment by razvand** [comment]
@StefanJum , this needs to be rebased again.

**Comment by StefanJum** [comment]
Done @razvand

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
