### PR TITLE
Stefan jum/guides/add bincompat

### PR DESCRIPTION
**Pull request by StefanJum**
Rebased on top of #315 for the linter output. Will remove that after it is merged.

### CODE REVIEW

**Comment by razvand** [comment]
@StefanJum , I made a new commit with updates to the initial content. Check it out.

**Comment by StefanJum** [comment]
@razvand I pushed some changes in a new commit, mainly regarding linting. See if it's ok and then squash and force push.

2 questions:
1. What do we need to add to the intro for `TODO: x86_64, Linux, KVM, PIE`?
2. Will we merge the elfloader updates with the scripts and everything in time for the hackathon?

**Comment by razvand** [comment]
@StefanJum , I'm filling the TODOs before merging.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
