### PR TITLE
Fixing some typos in the documentation

### PR DESCRIPTION
**Pull request by fabbing**
I've been learning about Unikraft and have started by going through the documentation, which I've found really interesting and instructive! Thanks for the effort you've put into it.
I found a few typos or corrections that could be made, so here's a little PR to improve it a bit. :)

### CODE REVIEW

**Review by razvand — CHANGES_REQUESTED** [review]
Hi, @fabbing , thanks so much for your contribution.

Please sign off your commits. Maybe you would also use a single e-mail address, right now you're using both `fabrice@tarides.com` and `fabbing@free.fr`.

Please also prefix your commit message with the "area" of change: `docs/cli`, `docs/concepts`, `docs/internals`.

**Comment by fabbing** [comment]
Thanks for pointing this out @razvand! I think the commits now look as expected.

**Comment by razvand** [comment]
> Thanks for pointing this out @razvand! I think the commits now look as expected.

Hi, @fabbing , sorry for the late reply.

Yes, looks good. Please sign off your commits, as told in the [submission checklist](https://unikraft.org/docs/contributing/unikraft#developers-certificate-of-origin). That is, add the line to each commit message:

```text
Signed-off-by: Fabrice Buoro <fabbing@free.fr>
```

Also use your full name in the commit author. You can use a command such as:

```console
GIT_COMMITTER_EMAIL=fabbing@free.fr GIT_COMMITTER_NAME='Fabrice Buoro" GIT_AUTHOR_EMAIL=fabbing@free.fr GIT_AUTHOR_NAME='Fabrice Buoro" git commit --amend --reset-author
```

**Comment by razvand** [comment]
> > Thanks for pointing this out @razvand! I think the commits now look as expected.
> 
> Hi, @fabbing , sorry for the late reply.
> 
> Yes, looks good. Please sign off your commits, as told in the [submission checklist](https://unikraft.org/docs/contributing/unikraft#developers-certificate-of-origin). That is, add the line to each commit message:
> 
> ```
> Signed-off-by: Fabrice Buoro <fabbing@free.fr>
> ```
> 
> Also use your full name in the commit author. You can use a command such as:
> 
> ```
> GIT_COMMITTER_EMAIL=fabbing@free.fr GIT_COMMITTER_NAME='Fabrice Buoro" GIT_AUTHOR_EMAIL=fabbing@free.fr GIT_AUTHOR_NAME='Fabrice Buoro" git commit --amend --reset-author
> ```

**Comment by razvand** [comment]
Also, @fabbing , take care of the merge conflicts.

**Comment by fabbing** [comment]
Ironically, I must have missed this part of the documentation, sorry.

Rebased, fixed commit messages that were too long, and signed the commits properly.

**Review by StefanJum — APPROVED** [review]
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
